type  Member @entity {
  id: String!
  address: Bytes!
  membershipContract: SDVVVMembership!
  membership: Membership  @derivedFrom(field: "owner")
}

type SDVVVMembership @entity {
  id: String!
  address: Bytes!
  deploymentTrxHash: Bytes!
  deploymentBlockNumber: BigInt!
  deploymentTimestamp: BigInt!
  baseUri: String!
  suffix: String!
  trustedEntity: [TrustedEntity!] @derivedFrom(field: "membershipContract")
  defaultAdmin: [DefaultAdmin!] @derivedFrom(field: "membershipContract")
  members: [Member!] @derivedFrom(field: "membershipContract")
  tokens: [Membership!] @derivedFrom(field: "membershipContract")
}

type TrustedEntity @entity {
  id: String!
  address: Bytes!
  activeSince: BigInt!
  activeSinceBlockNumber: BigInt!
  activeSinceTrxHash: Bytes!
  membershipContract: SDVVVMembership!
  addedBy: Bytes!
}

type DefaultAdmin @entity {
  id: String!
  address: Bytes!
  activeSince: BigInt!
  activeSinceBlockNumber: BigInt!
  activeSinceTrxHash: Bytes!
  membershipContract: SDVVVMembership!
  addedBy: Bytes!
}

type Membership @entity {
  id: String!
  tokenId: BigInt!
  activeSince: BigInt!
  blockNumber: BigInt!
  transactionHash: Bytes!
  isActive: Boolean!
  tierLevel: BigInt!
  lastUpdate: BigInt!
  membershipContract: SDVVVMembership!
  owner: Member!
}

type PerksRegistry @entity {
  id: String!
  address: Bytes!
  deploymentTrxHash: Bytes!
  deploymentBlockNumber: BigInt!
  deploymentTimestamp: BigInt!
  membershipContract: SDVVVMembership!
  perks: [Perk!] @derivedFrom(field: "perksRegistry")
}

type Perk @entity {
  id: String!
  perkId: BigInt!
  name: String!
  perkUri: String!
  isPerkActive: Boolean!
  perksRegistry: PerksRegistry!
  createdOn: BigInt!
  creationTrxHash: Bytes!
  eligiblePerksForTier: [BigInt!]
  lastUpdatedOn: BigInt!
  lastUpdateTrxHash: Bytes!
}
