type  Member @entity {
  id: String!
  address: Bytes!
  membershipContract: SDVVVMembership!
  membership: Membership  @derivedFrom(field: "owner")
}

type SDVVVMembership @entity {
  id: String!
  address: Bytes!
  deploymentTrxHash: Bytes!
  deploymentBlockNumber: BigInt!
  deploymentTimestamp: BigInt!
  baseUri: String!
  suffix: String!
  trustedEntity: [TrustedEntity!] @derivedFrom(field: "membershipContract")
  defaultAdmin: [DefaultAdmin!] @derivedFrom(field: "membershipContract")
  members: [Member!] @derivedFrom(field: "membershipContract")
  tokens: [Membership!] @derivedFrom(field: "membershipContract")
}

type TrustedEntity @entity {
  id: String!
  address: Bytes!
  activeSince: BigInt!
  activeSinceBlockNumber: BigInt!
  activeSinceTrxHash: Bytes!
  membershipContract: SDVVVMembership!
  addedBy: Bytes!
}

type DefaultAdmin @entity {
  id: String!
  address: Bytes!
  activeSince: BigInt!
  activeSinceBlockNumber: BigInt!
  activeSinceTrxHash: Bytes!
  membershipContract: SDVVVMembership!
  addedBy: Bytes!
}

type Membership @entity {
  id: String!
  tokenId: BigInt!
  activeSince: BigInt!
  blockNumber: BigInt!
  transactionHash: Bytes!
  isActive: Boolean!
  tierLevel: BigInt!
  lastUpdate: BigInt!
  membershipContract: SDVVVMembership!
  owner: Member!
}

type PerkDeactivated @entity(immutable: true) {
  id: Bytes!
  perkId: BigInt! # uint256
  caller: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type PerkEligibilityUpdated @entity(immutable: true) {
  id: Bytes!
  perkId: BigInt! # uint256
  _existingEligibleTierLevels: [BigInt!]! # uint256[]
  _updatedEligibleTierLevels: [BigInt!]! # uint256[]
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type PerkRegistered @entity(immutable: true) {
  id: Bytes!
  perkId: BigInt! # uint256
  name: String! # string
  uri: String! # string
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type SDVPerksRegistryRoleAdminChanged @entity(immutable: true) {
  id: Bytes!
  role: Bytes! # bytes32
  previousAdminRole: Bytes! # bytes32
  newAdminRole: Bytes! # bytes32
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type SDVPerksRegistryRoleGranted @entity(immutable: true) {
  id: Bytes!
  role: Bytes! # bytes32
  account: Bytes! # address
  sender: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type SDVPerksRegistryRoleRevoked @entity(immutable: true) {
  id: Bytes!
  role: Bytes! # bytes32
  account: Bytes! # address
  sender: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

